- hosts: localhost
  tasks:
    - name: Resource group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: westeurope
        tags:
          delete: never
          environment: test

    - name: Service bus
      azure_rm_servicebus:
        name: "sms-{{ sha256 }}"
        sku: basic
        resource_group: "{{ resource_group }}"

    - name: Plan
      azure_rm_appserviceplan:
        name: "{{ plan }}"
        resource_group: "{{ resource_group }}"
        sku: B1
        is_linux: true
        number_of_workers: 1 
        
    - name: Create main web app
      azure_rm_webapp:
        resource_group: "{{ resource_group }}"
        name: "gateway-{{ sha256 }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ plan }}"
          sku: B1
          is_linux: true
          number_of_workers: 1
        container_settings:
          name: ptrdiff/segmentation
